[package]
name = "traffic-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
flume = "0.11.1"
log = "0.4.26"
ipnet = "2.11.0"
chrono = "0.4.41"

